# Generated by Django 5.0.6 on 2024-06-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_date', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('reason', models.TextField(default='loan')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('term', models.IntegerField()),
                ('appliedAt', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.loancategorys')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_customer', to='Manager.customer')),
            ],
        ),
    ]
