# Generated by Django 5.0.6 on 2024-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0002_alter_loanapplication_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='status_date',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='interestRate',
            field=models.IntegerField(default='2'),
        ),
    ]
