# Generated by Django 5.0.6 on 2024-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0003_remove_loanapplication_status_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interestRate',
            field=models.IntegerField(default='2'),
        ),
    ]
