# Generated by Django 5.0.6 on 2024-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0005_alter_loanapplication_interestrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interestRate',
            field=models.IntegerField(),
        ),
    ]
