# Generated by Django 5.0.6 on 2024-06-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0006_alter_loanapplication_interestrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='interestRate',
        ),
    ]
