# Generated by Django 5.0.6 on 2024-06-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0007_remove_loanapplication_interestrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='customerID',
        ),
    ]
