# Generated by Django 5.0.6 on 2024-06-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0008_remove_loanapplication_customerid'),
        ('Manager', '0002_loanusers_users_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='userID',
            field=models.ForeignKey(default='18c8ca88c8834e4e921d007110232d74', on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to='Manager.users'),
            preserve_default=False,
        ),
    ]
