# Generated by Django 5.0.6 on 2024-06-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0009_loanapplication_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='userID',
            new_name='customerID',
        ),
    ]
