# Generated by Django 5.0.6 on 2024-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0010_rename_userid_loanapplication_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interestRate',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
    ]
