# Generated by Django 5.0.6 on 2024-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0013_loanapplication_interestrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loanNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
