# Generated by Django 5.0.6 on 2024-07-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0016_alter_loanapplication_loannumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loanNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
