# Generated by Django 5.0.6 on 2024-07-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0017_alter_loanapplication_loannumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='amount',
            new_name='principleAmount',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='interestAmount',
            field=models.IntegerField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='totalAmount',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
