# Generated by Django 5.0.6 on 2024-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0018_rename_amount_loanapplication_principleamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='disbursedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pendingAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='recoveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
