# Generated by Django 5.0.6 on 2024-08-08 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0019_loanapplication_disbursedat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='principleAmount',
            new_name='principalAmount',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_payment_date', models.DateTimeField()),
                ('loanNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_number', to='Loan.loanapplication')),
            ],
        ),
    ]
