# Generated by Django 5.0.6 on 2024-08-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0020_rename_principleamount_loanapplication_principalamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.IntegerField(default=1),
        ),
    ]
