# Generated by Django 5.0.6 on 2024-06-13 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('userRole', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, default='Soroti,Uganda', max_length=250, null=True)),
                ('designation', models.CharField(max_length=250)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loanCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanName', models.CharField(max_length=250)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
