# Generated by Django 5.0.6 on 2024-06-13 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0008_remove_loanapplication_customerid'),
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=250)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, default='Soroti,Uganda', max_length=250, null=True)),
                ('designation', models.CharField(max_length=250)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('userRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.loanusers')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
