# Generated by Django 5.0.6 on 2024-06-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_loanusers_users_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userID',
            new_name='customerID',
        ),
    ]
