# Generated by Django 5.0.6 on 2024-07-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_rename_userid_users_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanType', models.CharField(max_length=250)),
                ('typicalPeriod', models.CharField(max_length=500)),
                ('commonUseCases', models.CharField(max_length=500)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
