# Generated by Django 5.0.6 on 2024-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_loanterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userRole',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
