# Generated by Django 5.0.6 on 2024-07-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_alter_users_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.loanusers'),
        ),
    ]
